[2025-07-05T11:45:41.527+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.download_and_process manual__2025-07-05T09:50:56.678578+00:00 map_index=0 [queued]>
[2025-07-05T11:45:41.829+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.download_and_process manual__2025-07-05T09:50:56.678578+00:00 map_index=0 [queued]>
[2025-07-05T11:45:41.830+0000] {taskinstance.py:1359} INFO - Starting attempt 3 of 2
[2025-07-05T11:45:42.136+0000] {taskinstance.py:1380} INFO - Executing <Mapped(_PythonDecoratedOperator): download_and_process> on 2025-07-05 09:50:56.678578+00:00
[2025-07-05T11:45:42.320+0000] {standard_task_runner.py:57} INFO - Started process 269 to run task
[2025-07-05T11:45:42.431+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'download_and_process', 'manual__2025-07-05T09:50:56.678578+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_pipeline.py', '--cfg-path', '/tmp/tmpyiy8j3fj', '--map-index', '0']
[2025-07-05T11:45:42.530+0000] {standard_task_runner.py:85} INFO - Job 137: Subtask download_and_process
[2025-07-05T11:45:43.234+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-05T11:45:44.042+0000] {task_command.py:415} INFO - Running <TaskInstance: weather_data_pipeline.download_and_process manual__2025-07-05T09:50:56.678578+00:00 map_index=0 [running]> on host 63adaf3f7c0d
[2025-07-05T11:46:33.822+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1645, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2283, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/mappedoperator.py", line 724, in render_template_fields
    mapped_kwargs, seen_oids = self._expand_mapped_kwargs(context, session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 527, in _expand_mapped_kwargs
    op_kwargs, resolved_oids = super()._expand_mapped_kwargs(context, session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/mappedoperator.py", line 584, in _expand_mapped_kwargs
    return self._get_specified_expand_input().resolve(context, session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/expandinput.py", line 200, in resolve
    data = {k: self._expand_mapped_field(k, v, context, session=session) for k, v in self.value.items()}
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/expandinput.py", line 200, in <dictcomp>
    data = {k: self._expand_mapped_field(k, v, context, session=session) for k, v in self.value.items()}
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/expandinput.py", line 186, in _expand_mapped_field
    raise TypeError(f"can't map over value of type {type(value)}")
TypeError: can't map over value of type <class 'NoneType'>
[2025-07-05T11:46:33.830+0000] {taskinstance.py:1981} ERROR - Unable to unmap task to determine if we need to send an alert email
[2025-07-05T11:46:33.831+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=weather_data_pipeline, task_id=download_and_process, map_index=0, execution_date=20250705T095056, start_date=20250705T114541, end_date=20250705T114633
[2025-07-05T11:46:33.932+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 137 for task download_and_process (can't map over value of type <class 'NoneType'>; 269)
