[2025-07-05T11:46:18.733+0000] {taskinstance.py:1147} INFO - Dependencies not met for <TaskInstance: weather_data_pipeline.download_and_process manual__2025-07-05T10:11:14.401964+00:00 map_index=2 [None]>, dependency 'Trigger Rule' FAILED: Task's trigger rule 'all_success' requires all upstream tasks to have succeeded, but found 1 non-success(es). upstream_states=_UpstreamTIStates(success=0, skipped=0, failed=0, upstream_failed=0, removed=0, done=0, success_setup=0, skipped_setup=0), upstream_task_ids={'list_files'}
[2025-07-05T11:46:18.744+0000] {local_task_job_runner.py:154} INFO - Task is not able to be run
[2025-07-05T11:46:42.518+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.download_and_process manual__2025-07-05T10:11:14.401964+00:00 map_index=2 [queued]>
[2025-07-05T11:46:42.822+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.download_and_process manual__2025-07-05T10:11:14.401964+00:00 map_index=2 [queued]>
[2025-07-05T11:46:42.911+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 3
[2025-07-05T11:46:43.121+0000] {taskinstance.py:1380} INFO - Executing <Mapped(_PythonDecoratedOperator): download_and_process> on 2025-07-05 10:11:14.401964+00:00
[2025-07-05T11:46:43.315+0000] {standard_task_runner.py:57} INFO - Started process 352 to run task
[2025-07-05T11:46:43.323+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'download_and_process', 'manual__2025-07-05T10:11:14.401964+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/weather_data_pipeline.py', '--cfg-path', '/tmp/tmp_jgw_f4e', '--map-index', '2']
[2025-07-05T11:46:43.416+0000] {standard_task_runner.py:85} INFO - Job 152: Subtask download_and_process
[2025-07-05T11:46:43.712+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-05T11:46:44.514+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2025-07-05T11:46:44.612+0000] {process_utils.py:131} INFO - Sending 15 to group 352. PIDs of all processes in the group: [352]
[2025-07-05T11:46:44.616+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 352
